/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

import br.edu.ifnmg.poo.trabalhofinalpoo.dao.ProfessorDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Professor;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Janela para inclusao, edição e exclusão de professores
 * 
 * @author Mateus Felipe Mendes <mfdjm at aluno dot ifnmg dot edu dot br>
 * @author Felipe Rocha Boa-Sorte <frb at aluno dot ifnmg dot edu dot br>
 * @author André Vinicius Mendes Barros <avmb at aluno dot ifnmg dot edu dot br>
 * @version 0.1.0, 18/12/2020
 */
public class CadastrarProfessor extends javax.swing.JDialog {

    /**
     * Modelo para manutenção de dados a serem apresentado na listagem da
     * interface gráfica.
     */
    private DefaultListModel<Professor> lstProfessoresModel;
    
    /**
     * Retém o índice do professor selecionado para referências de processamentos
     * entre vários métodos.
     */
    private int indiceProfessorSelecionado;
    
    /**
     * Iniciliza elementos da nova janela
     */
    public CadastrarProfessor(TelaPrincipal tela, boolean modal) {
        super(tela, true);
        // Modelo padrão para elementos em listagens
        lstProfessoresModel = new DefaultListModel<>();

        // Recupera todos os registros do banco de dados
        List<Professor> professores = new ProfessorDao().localizarTodos();

        // Acrescente objetos do tipo Professor recuperados do banco de dados
        // ao elemento de listagem. Aqui são incluídas as referências completas
        // aos estados de cada objeto (id, descrição e concluída)
        lstProfessoresModel.addAll(professores);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenu = new javax.swing.JPopupMenu();
        mnuEditar = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        pnlCadastroProfessor = new javax.swing.JPanel();
        pnlListaProfessores = new javax.swing.JPanel();
        pnlAreaDados = new javax.swing.JPanel();
        pnlDados = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JTextField();
        lblDadosProfessor = new javax.swing.JLabel();
        btnSalvarDados = new javax.swing.JButton();
        btnCancelarDados = new javax.swing.JButton();
        lblListaProfessores = new javax.swing.JLabel();
        scrListaProfessores = new javax.swing.JScrollPane();
        lstProfessores = new javax.swing.JList<>();
        lblObservacao = new javax.swing.JLabel();

        mnuEditar.setText("Editar");
        mnuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarActionPerformed(evt);
            }
        });
        popUpMenu.add(mnuEditar);

        mnuExcluir.setText("Excluir");
        mnuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExcluirActionPerformed(evt);
            }
        });
        popUpMenu.add(mnuExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Instrutores");
        setResizable(false);

        pnlCadastroProfessor.setBackground(new java.awt.Color(255, 255, 255));

        pnlListaProfessores.setBackground(new java.awt.Color(255, 255, 255));

        pnlAreaDados.setBackground(new java.awt.Color(255, 255, 255));

        pnlDados.setBackground(new java.awt.Color(255, 255, 255));
        pnlDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(0, 0, 0));
        lblCPF.setText("CPF");

        lblNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNascimento.setForeground(new java.awt.Color(0, 0, 0));
        lblNascimento.setText("Data de nasc.");

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));

        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
        txtCPF.setForeground(new java.awt.Color(0, 0, 0));
        txtCPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCPFActionPerformed(evt);
            }
        });

        txtDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        txtDataNascimento.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addComponent(lblNascimento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDadosLayout.createSequentialGroup()
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNome)
                            .addComponent(lblCPF))
                        .addGap(57, 57, 57)
                        .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimento)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblDadosProfessor.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDadosProfessor.setForeground(new java.awt.Color(0, 0, 0));
        lblDadosProfessor.setText("Cadastrar novo instrutor");

        btnSalvarDados.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvarDados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarDados.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvarDados.setText("Salvar");
        btnSalvarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarDadosActionPerformed(evt);
            }
        });

        btnCancelarDados.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarDados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarDados.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarDados.setText("Cancelar");
        btnCancelarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarDadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAreaDadosLayout = new javax.swing.GroupLayout(pnlAreaDados);
        pnlAreaDados.setLayout(pnlAreaDadosLayout);
        pnlAreaDadosLayout.setHorizontalGroup(
            pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaDadosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadosProfessor)
                    .addGroup(pnlAreaDadosLayout.createSequentialGroup()
                        .addComponent(btnSalvarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pnlAreaDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelarDados, btnSalvarDados});

        pnlAreaDadosLayout.setVerticalGroup(
            pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaDadosLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(lblDadosProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarDados)
                    .addComponent(btnSalvarDados))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lblListaProfessores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblListaProfessores.setForeground(new java.awt.Color(0, 0, 0));
        lblListaProfessores.setText("Lista de instrutores");

        lstProfessores.setBackground(new java.awt.Color(255, 255, 255));
        lstProfessores.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstProfessores.setForeground(new java.awt.Color(0, 0, 0));
        lstProfessores.setModel(lstProfessoresModel);
        lstProfessores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstProfessoresMouseReleased(evt);
            }
        });
        scrListaProfessores.setViewportView(lstProfessores);

        lblObservacao.setForeground(new java.awt.Color(102, 102, 102));
        lblObservacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObservacao.setText("Para excluir ou editar, clique com o botão direito na seleção.");

        javax.swing.GroupLayout pnlListaProfessoresLayout = new javax.swing.GroupLayout(pnlListaProfessores);
        pnlListaProfessores.setLayout(pnlListaProfessoresLayout);
        pnlListaProfessoresLayout.setHorizontalGroup(
            pnlListaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaProfessoresLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlListaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlAreaDados, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlListaProfessoresLayout.createSequentialGroup()
                        .addComponent(lblObservacao)
                        .addGap(25, 25, 25))))
            .addGroup(pnlListaProfessoresLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlListaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlListaProfessoresLayout.createSequentialGroup()
                        .addComponent(lblListaProfessores)
                        .addGap(479, 479, 479))
                    .addComponent(scrListaProfessores, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlListaProfessoresLayout.setVerticalGroup(
            pnlListaProfessoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlListaProfessoresLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblListaProfessores)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrListaProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(pnlAreaDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout pnlCadastroProfessorLayout = new javax.swing.GroupLayout(pnlCadastroProfessor);
        pnlCadastroProfessor.setLayout(pnlCadastroProfessorLayout);
        pnlCadastroProfessorLayout.setHorizontalGroup(
            pnlCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCadastroProfessorLayout.createSequentialGroup()
                .addComponent(pnlListaProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlCadastroProfessorLayout.setVerticalGroup(
            pnlCadastroProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlListaProfessores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroProfessor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Resposta ao clique sobre o botão "Salvar"
     * @param evt Evento capturado
     */
    private void btnSalvarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarDadosActionPerformed
        // Cria um objeto a partir dos dados informados pelo usuário
        Professor professor = new Professor();
        professor.setNome(txtNome.getText());
        professor.setCpf(Integer.parseInt(txtCPF.getText()));
        professor.setNascimento(txtDataNascimento.getText());

        // Executa o salvamento do estado do objeto no banco de dados
        Long id = new ProfessorDao().salvar(professor);

        // Importante! Se o objeto criado não for atrelado a seu id no banco
        // de dados, o objeto fica desconexo e as futuras alterações de seu
        // estado gerarão um novo registro
        professor.setId(id);

        // Atualiza a listagem por meio da inserção direta do elemento recém-criado.
        // Poderia ser uma nova consulta ao banco de dados para recuperar todos
        // os registros. (!!!) Isto seria útil em um sistema multiusuário.
        lstProfessoresModel.addElement(professor);

        // Restaura o estado inicial dos componentes da janela.
        limparCampos();
    }//GEN-LAST:event_btnSalvarDadosActionPerformed

    private void btnCancelarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarDadosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCancelarDadosActionPerformed

    private void txtCPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCPFActionPerformed

    /**
     * Resposta ao clique sobre a opção "Editar" do menu de contexto.
     * 
     * @param evt Evento capturado
     */
    private void mnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarActionPerformed
        EditarProfessor editarProfessor
                = new EditarProfessor(lstProfessores.getSelectedValue(), this, true);
        // this -> referencia a janela principal
        editarProfessor.setLocationRelativeTo(this);
        editarProfessor.setVisible(true);
    }//GEN-LAST:event_mnuEditarActionPerformed

    /**
     * Resposta ao clique sobre a opção "Excluir" do menu de contexto.
     * 
     * @param evt Evento capturado
     */
    private void mnuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExcluirActionPerformed
        new ProfessorDao().excluir(lstProfessoresModel.get(indiceProfessorSelecionado));

        // Exclui graficamente 
        lstProfessoresModel.remove(lstProfessores.getSelectedIndex());
    }//GEN-LAST:event_mnuExcluirActionPerformed

    /**
     * Resposta ao clique com botão direito sobre elementos da listagem de professores.
     * 
     * @param evt Evento capturado
     */
    private void lstProfessoresMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstProfessoresMouseReleased
        if (evt.getButton() == MouseEvent.BUTTON3
                && lstProfessores.getModel().getSize() > 0) {
            indiceProfessorSelecionado = lstProfessores.locationToIndex(evt.getPoint());
            lstProfessores.setSelectedIndex(indiceProfessorSelecionado);
            popUpMenu.show(lstProfessores, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_lstProfessoresMouseReleased
    
    /**
     * Restaura estado inicial dos campos do formulário.
     */
    private void limparCampos() {
        // "Descrição" vazia
        txtCPF.setText(null);
        txtDataNascimento.setText(null);
        txtNome.setText(null);
        
        // Seleção da "Descrição" para nova digitação
        txtNome.requestFocus();
    }
    
    /**
     * Permite a atualização de um professor que foi editada em outra janela.
     * 
     * @param professor A ser acrescentado a listagem de professores
     */
    void atualizarModelo(Professor professor) {
        lstProfessoresModel.set(indiceProfessorSelecionado, professor);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarDados;
    private javax.swing.JButton btnSalvarDados;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDadosProfessor;
    private javax.swing.JLabel lblListaProfessores;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JList<Professor> lstProfessores;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JPanel pnlAreaDados;
    private javax.swing.JPanel pnlCadastroProfessor;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlListaProfessores;
    private javax.swing.JPopupMenu popUpMenu;
    private javax.swing.JScrollPane scrListaProfessores;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
