/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

import br.edu.ifnmg.poo.trabalhofinalpoo.dao.DiscenteDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Discente;
import java.awt.event.MouseEvent;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Classe para representar a tela do discente no sistema escolar
 * 
 * @author Mateus Felipe Mendes <mfdjm at aluno dot ifnmg dot edu dot br>
 * @author Felipe Rocha Boa-Sorte <frb at aluno dot ifnmg dot edu dot br>
 * @author André Vinicius Mendes Barros <avmb at aluno dot ifnmg dot edu dot br>
 * @version 0.1.0, 18/12/2020
 */
public class CadastrarDiscente extends javax.swing.JFrame {

    /**
     * Modelo para manutenção da lista de discentes a serem apresentadas na listagem da
     * interface gráfica.
     */
    private DefaultListModel<Discente> lstDiscentesModel;
    
    /**
     * Retém o índice da avaliação selecionada para referências de processamentos
     * entre vários métodos.
     */
    private int indiceDiscenteSelecionado;
    
    /**
     * Construtor padrão de CadastrarDiscente
     */
    public CadastrarDiscente() {
        
        lstDiscentesModel = new DefaultListModel<>();

        // Recupera todos os registros do banco de dados
        List<Discente> discentes = new DiscenteDao().localizarTodos();

        // Acrescente objetos do tipo Tarefa recuperados do banco de dados
        // ao elemento de listagem. Aqui são incluídas as referências completas
        // aos estados de cada objeto (id, descrição e concluída)
        lstDiscentesModel.addAll(discentes);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenu = new javax.swing.JPopupMenu();
        mnuEditar = new javax.swing.JMenuItem();
        mnuExcluir = new javax.swing.JMenuItem();
        pnlCadastroDiscente = new javax.swing.JPanel();
        lblListaDiscentes = new javax.swing.JLabel();
        scrListaAlunos = new javax.swing.JScrollPane();
        lstDiscentes = new javax.swing.JList<>();
        pnlAreaDados = new javax.swing.JPanel();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        pnlDados = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        lblCPF = new javax.swing.JLabel();
        lblNascimento = new javax.swing.JLabel();
        txtDataNascimento = new javax.swing.JTextField();
        txtCPF = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        lblDadosCadastrais = new javax.swing.JLabel();
        lblObservacao = new javax.swing.JLabel();

        mnuEditar.setText("Editar");
        mnuEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuEditarActionPerformed(evt);
            }
        });
        popUpMenu.add(mnuEditar);

        mnuExcluir.setText("Excluir");
        mnuExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExcluirActionPerformed(evt);
            }
        });
        popUpMenu.add(mnuExcluir);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Alunos");
        setResizable(false);

        pnlCadastroDiscente.setBackground(new java.awt.Color(255, 255, 255));

        lblListaDiscentes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblListaDiscentes.setForeground(new java.awt.Color(0, 0, 0));
        lblListaDiscentes.setText("Lista de discentes");

        scrListaAlunos.setBackground(new java.awt.Color(255, 255, 255));
        scrListaAlunos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));
        scrListaAlunos.setForeground(new java.awt.Color(0, 0, 0));

        lstDiscentes.setBackground(new java.awt.Color(255, 255, 255));
        lstDiscentes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstDiscentes.setForeground(new java.awt.Color(0, 0, 0));
        lstDiscentes.setModel(lstDiscentesModel);
        lstDiscentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstDiscentesMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                lstDiscentesMouseReleased(evt);
            }
        });
        scrListaAlunos.setViewportView(lstDiscentes);

        pnlAreaDados.setBackground(new java.awt.Color(255, 255, 255));

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        pnlDados.setBackground(new java.awt.Color(255, 255, 255));
        pnlDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));

        lblNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome.setForeground(new java.awt.Color(0, 0, 0));
        lblNome.setText("Nome");

        lblCPF.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF.setForeground(new java.awt.Color(0, 0, 0));
        lblCPF.setText("CPF");

        lblNascimento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNascimento.setForeground(new java.awt.Color(0, 0, 0));
        lblNascimento.setText("Data de nasc.");

        txtDataNascimento.setBackground(new java.awt.Color(255, 255, 255));
        txtDataNascimento.setForeground(new java.awt.Color(0, 0, 0));
        txtDataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoActionPerformed(evt);
            }
        });

        txtCPF.setBackground(new java.awt.Color(255, 255, 255));
        txtCPF.setForeground(new java.awt.Color(0, 0, 0));

        txtNome.setBackground(new java.awt.Color(255, 255, 255));
        txtNome.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlDadosLayout = new javax.swing.GroupLayout(pnlDados);
        pnlDados.setLayout(pnlDadosLayout);
        pnlDadosLayout.setHorizontalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNascimento)
                    .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPF, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(12, 12, 12)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(84, Short.MAX_VALUE))
        );
        pnlDadosLayout.setVerticalGroup(
            pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF)
                    .addComponent(txtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimento)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        lblDadosCadastrais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDadosCadastrais.setForeground(new java.awt.Color(0, 0, 0));
        lblDadosCadastrais.setText("Cadastrar novo discente");

        javax.swing.GroupLayout pnlAreaDadosLayout = new javax.swing.GroupLayout(pnlAreaDados);
        pnlAreaDados.setLayout(pnlAreaDadosLayout);
        pnlAreaDadosLayout.setHorizontalGroup(
            pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaDadosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadosCadastrais)
                    .addGroup(pnlAreaDadosLayout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        pnlAreaDadosLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnCancelar, btnSalvar});

        pnlAreaDadosLayout.setVerticalGroup(
            pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAreaDadosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblDadosCadastrais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAreaDadosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addGap(0, 25, Short.MAX_VALUE))
        );

        pnlAreaDadosLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnCancelar, btnSalvar});

        lblObservacao.setForeground(new java.awt.Color(102, 102, 102));
        lblObservacao.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblObservacao.setText("Para excluir ou editar, clique com o botão direito na seleção.");

        javax.swing.GroupLayout pnlCadastroDiscenteLayout = new javax.swing.GroupLayout(pnlCadastroDiscente);
        pnlCadastroDiscente.setLayout(pnlCadastroDiscenteLayout);
        pnlCadastroDiscenteLayout.setHorizontalGroup(
            pnlCadastroDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAreaDados, javax.swing.GroupLayout.PREFERRED_SIZE, 648, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroDiscenteLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlCadastroDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblObservacao)
                    .addGroup(pnlCadastroDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblListaDiscentes)
                        .addComponent(scrListaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(23, 23, 23))
        );
        pnlCadastroDiscenteLayout.setVerticalGroup(
            pnlCadastroDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCadastroDiscenteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblListaDiscentes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrListaAlunos, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblObservacao)
                .addGap(2, 2, 2)
                .addComponent(pnlAreaDados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroDiscente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlCadastroDiscente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ao clicar no botão Salvar, armazena os campos preenchidos na tela 
     * referente a discente, salva essa avaliação no banco de dados e adiciona-a na lista.
     * @param evt Evento capturado
     */
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        Discente discente = new Discente();
        discente.setNome(txtNome.getText());
        discente.setCpf(Integer.parseInt(txtCPF.getText()));
        discente.setNascimento(txtDataNascimento.getText());

        // Executa o salvamento do estado do objeto no banco de dados
        Long id = new DiscenteDao().salvar(discente);

        // Importante! Se o objeto criado não for atrelado a seu id no banco
        // de dados, o objeto fica desconexo e as futuras alterações de seu
        // estado gerarão um novo registro
        discente.setId(id);

        // Atualiza a listagem por meio da inserção direta do elemento recém-criado.
        // Poderia ser uma nova consulta ao banco de dados para recuperar todos
        // os registros. (!!!) Isto seria útil em um sistema multiusuário.
        lstDiscentesModel.addElement(discente);

        // Restaura o estado inicial dos componentes da janela.
        limparCampos();
    }//GEN-LAST:event_btnSalvarActionPerformed

    
    /**
     * Ao clicar no botão cancelar, fecha a tela atual
     * @param evt Evento capturado
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void txtDataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoActionPerformed

    /**
     * Resposta ao clique sobre a opção "Excluir" do menu de contexto.
     * @param evt Evento capturado  
     */
    private void mnuExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExcluirActionPerformed
         // TODO add your handling code here:

        // COm base no indice, devolve a tarefa
        new DiscenteDao().excluir(lstDiscentesModel.get(indiceDiscenteSelecionado));

        // Exclui graficamente 
        lstDiscentesModel.remove(lstDiscentes.getSelectedIndex());
    }//GEN-LAST:event_mnuExcluirActionPerformed

    /**
     * Resposta ao clique sobre a opção "Editar" do menu de contexto.
     * @param evt Evento capturado  
     */
    private void mnuEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuEditarActionPerformed
        EditarDiscente editarDiscente
                = new EditarDiscente(lstDiscentes.getSelectedValue(), this, true);
        // this -> referencia a janela principal
        editarDiscente.setLocationRelativeTo(this);
        editarDiscente.setVisible(true); 
    }//GEN-LAST:event_mnuEditarActionPerformed

    private void lstDiscentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDiscentesMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lstDiscentesMouseClicked

    /**
     * Verifica o indice do discente que foi clicado com o botão direito
     * e seleciona aquele discente na lista
     * @param evt Evento capturado
     */
    private void lstDiscentesMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstDiscentesMouseReleased
         // Button3 = botao direito
        if (evt.getButton() == MouseEvent.BUTTON3
                && lstDiscentes.getModel().getSize() > 0) {
            indiceDiscenteSelecionado = lstDiscentes.locationToIndex(evt.getPoint());
            lstDiscentes.setSelectedIndex(indiceDiscenteSelecionado);
            popUpMenu.show(lstDiscentes, evt.getX(), evt.getY());
        }
    }//GEN-LAST:event_lstDiscentesMouseReleased

    /**
     * Restaura o estado inicial dos campos do formulário.
     */
    private void limparCampos() {
        txtCPF.setText(null);
        txtDataNascimento.setText(null);
        txtNome.setText(null);
        
        txtNome.requestFocus();
    }
    /**
     * /**
     * Permite a atualização de um discente que foi editada em outra janela.
     * @param discente Discente que será acrescentada na listagem de discentes
     */
    void atualizarModelo(Discente discente) {
        lstDiscentesModel.set(indiceDiscenteSelecionado, discente);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblDadosCadastrais;
    private javax.swing.JLabel lblListaDiscentes;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblObservacao;
    private javax.swing.JList<Discente> lstDiscentes;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JMenuItem mnuExcluir;
    private javax.swing.JPanel pnlAreaDados;
    private javax.swing.JPanel pnlCadastroDiscente;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPopupMenu popUpMenu;
    private javax.swing.JScrollPane scrListaAlunos;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
