/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

import br.edu.ifnmg.poo.trabalhofinalpoo.dao.DiscenteDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Discente;

/**
 * Classe para representar a tela de edição de um discente no sistema escolar
 * @author felipe
 */
public class EditarDiscente extends javax.swing.JDialog {

    /**
     * Referência à janela de cadastro de discente que invocou esta janela de edição.
     */
    private final CadastrarDiscente cadastroDiscente;
    
    /**
     * Variável do tipo discente recebida para edicao.
     */
    private Discente discenteEmEdicao;
    
    /**
     * Construtor padrão de EditarDiscente
     */
    public EditarDiscente(Discente discente,
        CadastrarDiscente cadastroDiscente, boolean modal) {
        super(cadastroDiscente, modal);
        initComponents();
        
        this.cadastroDiscente = cadastroDiscente;
        this.discenteEmEdicao = discente;
        
        preencherDiscente(discente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditarDiscente = new javax.swing.JPanel();
        lblDadosEditar = new javax.swing.JLabel();
        pnlDadosEditar = new javax.swing.JPanel();
        lblNomeEditar = new javax.swing.JLabel();
        lblCPFEditar = new javax.swing.JLabel();
        lblNascimentoEditar = new javax.swing.JLabel();
        txtDataNascimentoEditar = new javax.swing.JTextField();
        txtCPFEditar = new javax.swing.JTextField();
        txtNomeEditar = new javax.swing.JTextField();
        btnSalvarEditar = new javax.swing.JButton();
        btnCancelarEditar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EditarDiscente");

        pnlEditarDiscente.setBackground(new java.awt.Color(255, 255, 255));

        lblDadosEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDadosEditar.setForeground(new java.awt.Color(0, 0, 0));
        lblDadosEditar.setText("Dados cadastrais");

        pnlDadosEditar.setBackground(new java.awt.Color(255, 255, 255));
        pnlDadosEditar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));

        lblNomeEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNomeEditar.setForeground(new java.awt.Color(0, 0, 0));
        lblNomeEditar.setText("Nome");

        lblCPFEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPFEditar.setForeground(new java.awt.Color(0, 0, 0));
        lblCPFEditar.setText("CPF");

        lblNascimentoEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNascimentoEditar.setForeground(new java.awt.Color(0, 0, 0));
        lblNascimentoEditar.setText("Data de nasc.");

        txtDataNascimentoEditar.setBackground(new java.awt.Color(255, 255, 255));
        txtDataNascimentoEditar.setForeground(new java.awt.Color(0, 0, 0));
        txtDataNascimentoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoEditarActionPerformed(evt);
            }
        });

        txtCPFEditar.setBackground(new java.awt.Color(255, 255, 255));
        txtCPFEditar.setForeground(new java.awt.Color(0, 0, 0));

        txtNomeEditar.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeEditar.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlDadosEditarLayout = new javax.swing.GroupLayout(pnlDadosEditar);
        pnlDadosEditar.setLayout(pnlDadosEditarLayout);
        pnlDadosEditarLayout.setHorizontalGroup(
            pnlDadosEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosEditarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDadosEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNascimentoEditar)
                    .addComponent(lblNomeEditar, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCPFEditar, javax.swing.GroupLayout.Alignment.LEADING))
                .addGap(12, 12, 12)
                .addGroup(pnlDadosEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCPFEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlDadosEditarLayout.setVerticalGroup(
            pnlDadosEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDadosEditarLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDadosEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeEditar)
                    .addComponent(txtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPFEditar)
                    .addComponent(txtCPFEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDadosEditarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimentoEditar)
                    .addComponent(txtDataNascimentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnSalvarEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvarEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvarEditar.setText("Salvar");
        btnSalvarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarEditarActionPerformed(evt);
            }
        });

        btnCancelarEditar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarEditar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarEditar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarEditar.setText("Cancelar");
        btnCancelarEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarEditarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlEditarDiscenteLayout = new javax.swing.GroupLayout(pnlEditarDiscente);
        pnlEditarDiscente.setLayout(pnlEditarDiscenteLayout);
        pnlEditarDiscenteLayout.setHorizontalGroup(
            pnlEditarDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarDiscenteLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlEditarDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadosEditar)
                    .addGroup(pnlEditarDiscenteLayout.createSequentialGroup()
                        .addComponent(btnSalvarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDadosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlEditarDiscenteLayout.setVerticalGroup(
            pnlEditarDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarDiscenteLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblDadosEditar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDadosEditar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlEditarDiscenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvarEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelarEditar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditarDiscente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditarDiscente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascimentoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoEditarActionPerformed

    /**
     * Ao clicar no botão Salvar, armazena os campos preenchidos na edição de discente,
     * salva essa alteração no bando de dados e adiciona a alteração na lista.
     * @param evt Evento capturado
     */
    private void btnSalvarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarEditarActionPerformed
        // TODO add your handling code here:
        discenteEmEdicao.setCpf(Integer.parseInt(txtCPFEditar.getText()));
        discenteEmEdicao.setNome(txtNomeEditar.getText());
        discenteEmEdicao.setNascimento(txtDataNascimentoEditar.getText());
        
        new DiscenteDao().salvar(discenteEmEdicao);
        cadastroDiscente.atualizarModelo(discenteEmEdicao);
        // fecha janela
        dispose();
    }//GEN-LAST:event_btnSalvarEditarActionPerformed

    /**
     * Ao clicar no botão cancelar, fecha a janela atual
     * @param evt Evento capturado
     */
    private void btnCancelarEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarEditarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarEditarActionPerformed

    /**
     * Extrai dados do discente recebido e popula os componentes da janela
     * com seus respectivos valores.
     * @param discente Objeto do tipo discente recebido
     */
    public void preencherDiscente(Discente discente){
        txtCPFEditar.setText(Integer.toString(discente.getCpf()));
        txtNomeEditar.setText(discente.getNome());
        txtDataNascimentoEditar.setText(discente.getNascimento());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarEditar;
    private javax.swing.JButton btnSalvarEditar;
    private javax.swing.JLabel lblCPFEditar;
    private javax.swing.JLabel lblDadosEditar;
    private javax.swing.JLabel lblNascimentoEditar;
    private javax.swing.JLabel lblNomeEditar;
    private javax.swing.JPanel pnlDadosEditar;
    private javax.swing.JPanel pnlEditarDiscente;
    private javax.swing.JTextField txtCPFEditar;
    private javax.swing.JTextField txtDataNascimentoEditar;
    private javax.swing.JTextField txtNomeEditar;
    // End of variables declaration//GEN-END:variables
}
