/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

import br.edu.ifnmg.poo.trabalhofinalpoo.dao.AvaliacaoDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.dao.DiscenteDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.dao.AulaDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Avaliacao;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Discente;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Aula;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 * Classe para representar a tela de edição de uma avaliação no sistema escolar
 * 
 * @author Mateus Felipe Mendes <mfdjm at aluno dot ifnmg dot edu dot br>
 * @author Felipe Rocha Boa-Sorte <frb at aluno dot ifnmg dot edu dot br>
 * @author André Vinicius Mendes Barros <avmb at aluno dot ifnmg dot edu dot br>
 * @version 0.1.0, 18/12/2020
 */
public class EditarAvaliacao extends javax.swing.JDialog {
    
    /**
     * Referência à janela de cadastro de avaliação que invocou esta janela de edição.
     */
    private final CadastrarAvaliacao cadastroAvaliacao;
    
    /**
     * Variável do tipo avaliação recebida para edicao.
     */
    private Avaliacao avaliacaoEmEdicao;
    
    /**
     * Modelo para manutenção da lista de discentes a serem apresentadas na listagem da
     * interface gráfica.
     */
    private DefaultListModel<Discente> lstDiscentesModel;
    
    /**
     * Modelo para manutenção da lista de aulas a serem apresentadas na listagem da
     * interface gráfica.
     */
    private DefaultListModel<Aula> lstAulasModel;

    /**
     * Construtor padrão de EditarAvaliacao
     */
    public EditarAvaliacao(Avaliacao avaliacao, 
        CadastrarAvaliacao cadastroProva, boolean modal) {
        super(cadastroProva, modal);
        
        lstDiscentesModel = new DefaultListModel<>();
        List<Discente> discentes = new DiscenteDao().localizarTodos();
        lstDiscentesModel.addAll(discentes);
        
        lstAulasModel = new DefaultListModel<>();
        List<Aula> aulas = new AulaDao().localizarTodos();
        lstAulasModel.addAll(aulas);
        
        initComponents();
        
        this.cadastroAvaliacao = cadastroProva;
        this.avaliacaoEmEdicao = avaliacao;
        
        preencherAvaliacao(avaliacao);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlEditarAvaliacao = new javax.swing.JPanel();
        lblAlunosAvaliacao = new javax.swing.JLabel();
        scrListaDiscentes = new javax.swing.JScrollPane();
        lstDiscentes = new javax.swing.JList<>();
        lblAulasAvaliacao = new javax.swing.JLabel();
        scrListaAulas = new javax.swing.JScrollPane();
        lstAulas = new javax.swing.JList<>();
        lblDetalhesAvaliacao = new javax.swing.JLabel();
        pnlDetalhesAvaliacao = new javax.swing.JPanel();
        lblNotasAvaliacao = new javax.swing.JLabel();
        pnlNotas = new javax.swing.JPanel();
        scrComentario = new javax.swing.JScrollPane();
        txtComentario = new javax.swing.JTextPane();
        lblComentarios = new javax.swing.JLabel();
        lblParteEscrita = new javax.swing.JLabel();
        txtParteEscrita = new javax.swing.JTextField();
        txtParteOral = new javax.swing.JTextField();
        lblParteOral = new javax.swing.JLabel();
        scrAprovado = new javax.swing.JScrollPane();
        txpAprovado = new javax.swing.JTextPane();
        btnSalvarAvaliacao = new javax.swing.JButton();
        btnCancelarAvaliacao = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar prova");

        pnlEditarAvaliacao.setBackground(new java.awt.Color(255, 255, 255));

        lblAlunosAvaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAlunosAvaliacao.setForeground(new java.awt.Color(0, 0, 0));
        lblAlunosAvaliacao.setText("Alunos cadastrados");

        lstDiscentes.setBackground(new java.awt.Color(255, 255, 255));
        lstDiscentes.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstDiscentes.setForeground(new java.awt.Color(0, 0, 0));
        lstDiscentes.setModel(lstDiscentesModel);
        scrListaDiscentes.setViewportView(lstDiscentes);

        lblAulasAvaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAulasAvaliacao.setForeground(new java.awt.Color(0, 0, 0));
        lblAulasAvaliacao.setText("Aulas lançadas");

        lstAulas.setBackground(new java.awt.Color(255, 255, 255));
        lstAulas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lstAulas.setForeground(new java.awt.Color(0, 0, 0));
        lstAulas.setModel(lstAulasModel);
        scrListaAulas.setViewportView(lstAulas);

        lblDetalhesAvaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDetalhesAvaliacao.setForeground(new java.awt.Color(0, 0, 0));
        lblDetalhesAvaliacao.setText("Detalhes da prova");

        pnlDetalhesAvaliacao.setBackground(new java.awt.Color(255, 255, 255));
        pnlDetalhesAvaliacao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));
        pnlDetalhesAvaliacao.setForeground(new java.awt.Color(112, 112, 112));

        lblNotasAvaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNotasAvaliacao.setForeground(new java.awt.Color(0, 0, 0));
        lblNotasAvaliacao.setText("Notas");

        pnlNotas.setBackground(new java.awt.Color(245, 245, 245));
        pnlNotas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));

        txtComentario.setBackground(new java.awt.Color(255, 255, 255));
        txtComentario.setForeground(new java.awt.Color(0, 0, 0));
        scrComentario.setViewportView(txtComentario);

        lblComentarios.setForeground(new java.awt.Color(0, 0, 0));
        lblComentarios.setText("Comentários");

        lblParteEscrita.setForeground(new java.awt.Color(0, 0, 0));
        lblParteEscrita.setText("Parte escrita");

        txtParteEscrita.setBackground(new java.awt.Color(255, 255, 255));
        txtParteEscrita.setForeground(new java.awt.Color(0, 0, 0));
        txtParteEscrita.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtParteEscrita.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));
        txtParteEscrita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParteEscritaActionPerformed(evt);
            }
        });

        txtParteOral.setBackground(new java.awt.Color(255, 255, 255));
        txtParteOral.setForeground(new java.awt.Color(0, 0, 0));
        txtParteOral.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtParteOral.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));
        txtParteOral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtParteOralActionPerformed(evt);
            }
        });

        lblParteOral.setForeground(new java.awt.Color(0, 0, 0));
        lblParteOral.setText("Parte oral");

        scrAprovado.setHorizontalScrollBar(null);

        txpAprovado.setEditable(false);
        txpAprovado.setBackground(new java.awt.Color(0, 204, 102));
        txpAprovado.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txpAprovado.setForeground(new java.awt.Color(0, 0, 0));
        scrAprovado.setViewportView(txpAprovado);

        javax.swing.GroupLayout pnlNotasLayout = new javax.swing.GroupLayout(pnlNotas);
        pnlNotas.setLayout(pnlNotasLayout);
        pnlNotasLayout.setHorizontalGroup(
            pnlNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotasLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblComentarios)
                    .addGroup(pnlNotasLayout.createSequentialGroup()
                        .addComponent(lblParteEscrita)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParteEscrita, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(lblParteOral)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtParteOral, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(scrAprovado, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrComentario))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnlNotasLayout.setVerticalGroup(
            pnlNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNotasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(pnlNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlNotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblParteEscrita)
                        .addComponent(txtParteEscrita, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblParteOral)
                        .addComponent(txtParteOral, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(scrAprovado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblComentarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrComentario, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        btnSalvarAvaliacao.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvarAvaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarAvaliacao.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvarAvaliacao.setText("Salvar");
        btnSalvarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarAvaliacaoActionPerformed(evt);
            }
        });

        btnCancelarAvaliacao.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarAvaliacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarAvaliacao.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarAvaliacao.setText("Cancelar");
        btnCancelarAvaliacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarAvaliacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlDetalhesAvaliacaoLayout = new javax.swing.GroupLayout(pnlDetalhesAvaliacao);
        pnlDetalhesAvaliacao.setLayout(pnlDetalhesAvaliacaoLayout);
        pnlDetalhesAvaliacaoLayout.setHorizontalGroup(
            pnlDetalhesAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesAvaliacaoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDetalhesAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDetalhesAvaliacaoLayout.createSequentialGroup()
                        .addComponent(lblNotasAvaliacao)
                        .addGap(55, 55, 55)
                        .addComponent(pnlNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlDetalhesAvaliacaoLayout.createSequentialGroup()
                        .addComponent(btnSalvarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 20, Short.MAX_VALUE))
        );
        pnlDetalhesAvaliacaoLayout.setVerticalGroup(
            pnlDetalhesAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesAvaliacaoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlDetalhesAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNotasAvaliacao)
                    .addComponent(pnlNotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDetalhesAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSalvarAvaliacao)
                    .addComponent(btnCancelarAvaliacao))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlEditarAvaliacaoLayout = new javax.swing.GroupLayout(pnlEditarAvaliacao);
        pnlEditarAvaliacao.setLayout(pnlEditarAvaliacaoLayout);
        pnlEditarAvaliacaoLayout.setHorizontalGroup(
            pnlEditarAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarAvaliacaoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlEditarAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlEditarAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(scrListaAulas, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                        .addComponent(scrListaDiscentes))
                    .addComponent(lblAlunosAvaliacao)
                    .addComponent(lblAulasAvaliacao))
                .addGap(25, 25, 25)
                .addGroup(pnlEditarAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetalhesAvaliacao)
                    .addComponent(pnlDetalhesAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        pnlEditarAvaliacaoLayout.setVerticalGroup(
            pnlEditarAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlEditarAvaliacaoLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pnlEditarAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDetalhesAvaliacao)
                    .addComponent(lblAlunosAvaliacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlEditarAvaliacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlEditarAvaliacaoLayout.createSequentialGroup()
                        .addComponent(scrListaDiscentes, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblAulasAvaliacao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(scrListaAulas, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDetalhesAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(pnlEditarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlEditarAvaliacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Ao clicar no botão Salvar, armazena os campos preenchidos na edição de avaliação,
     * salva essa alteração no bando de dados e adiciona a alteração na lista.
     * @param evt Evento capturado
     */
    private void btnSalvarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarAvaliacaoActionPerformed
        avaliacaoEmEdicao.setNotaParteEscrita(Integer.parseInt(txtParteEscrita.getText()));
        avaliacaoEmEdicao.setNotaParteOral(txtParteOral.getText());
        avaliacaoEmEdicao.setComentario(txtComentario.getText());
        avaliacaoEmEdicao.setIdDiscente(lstDiscentes.getSelectedValue().getId().intValue());
        avaliacaoEmEdicao.setIdAula(lstAulas.getSelectedValue().getId().intValue());
               
        new AvaliacaoDao().salvar(avaliacaoEmEdicao);
        cadastroAvaliacao.atualizarModelo(avaliacaoEmEdicao);

        dispose();     
    }//GEN-LAST:event_btnSalvarAvaliacaoActionPerformed
    
    /**
     * Ao clicar no botão cancelar, fecha a janela atual
     * @param evt Evento capturado
     */
    private void btnCancelarAvaliacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarAvaliacaoActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarAvaliacaoActionPerformed

    private void txtParteEscritaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParteEscritaActionPerformed
        
    }//GEN-LAST:event_txtParteEscritaActionPerformed

    private void txtParteOralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtParteOralActionPerformed
        if(estaAprovadoEscrita(Integer.parseInt(txtParteEscrita.getText())) && 
                estaAprovadoOral(txtParteOral.getText())){
            txpAprovado.setText("APROVADO");
        }
        else {
            txpAprovado.setText("REPROVADO");
        }        
    }//GEN-LAST:event_txtParteOralActionPerformed

    /**
     * Extrai dados da avaliação recebida e popula os componentes da janela
     * com seus respectivos valores.
     * @param avaliacao Objeto do tipo avaliação recebido
     */
    public void preencherAvaliacao(Avaliacao avaliacao){
        txtParteEscrita.setText(Integer.toString(avaliacao.getNotaParteEscrita()));
        txtParteOral.setText(avaliacao.getNotaParteOral());
        txtComentario.setText(avaliacao.getComentario());
        lstDiscentes.setSelectedIndex(avaliacao.getIdDiscente());
        lstAulas.setSelectedIndex(avaliacao.getIdAula());
    }
    
        /**
     * Verifica se o discente que realizou determinada avaliação
     * foi reprovado ou aprovado na parte escrita
     * @param parteEscrita Nota referente a parte escrita
     * @return Se o aluno foi aprovado (true) ou reprovado (false)
     */
    private boolean estaAprovadoEscrita(int parteEscrita){
        if(parteEscrita >= 98 && parteEscrita <= 100){
                return true;
        }
        return false;
    }
    
    /**
     * Verifica se o discente que realizou determinada avaliação
     * foi reprovado ou aprovado na parte oral
     * @param parteOral Nota referente a parte oral
     * @return Se o aluno foi aprovado (true) ou reprovado (false)
     */
    private boolean estaAprovadoOral(String parteOral){
        return ("D".equals(parteOral) 
                || "YD".equals(parteOral)
                || "T".equals(parteOral));
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAvaliacao;
    private javax.swing.JButton btnSalvarAvaliacao;
    private javax.swing.JLabel lblAlunosAvaliacao;
    private javax.swing.JLabel lblAulasAvaliacao;
    private javax.swing.JLabel lblComentarios;
    private javax.swing.JLabel lblDetalhesAvaliacao;
    private javax.swing.JLabel lblNotasAvaliacao;
    private javax.swing.JLabel lblParteEscrita;
    private javax.swing.JLabel lblParteOral;
    private javax.swing.JList<br.edu.ifnmg.poo.trabalhofinalpoo.entity.Aula> lstAulas;
    private javax.swing.JList<Discente> lstDiscentes;
    private javax.swing.JPanel pnlDetalhesAvaliacao;
    private javax.swing.JPanel pnlEditarAvaliacao;
    private javax.swing.JPanel pnlNotas;
    private javax.swing.JScrollPane scrAprovado;
    private javax.swing.JScrollPane scrComentario;
    private javax.swing.JScrollPane scrListaAulas;
    private javax.swing.JScrollPane scrListaDiscentes;
    private javax.swing.JTextPane txpAprovado;
    private javax.swing.JTextPane txtComentario;
    private javax.swing.JTextField txtParteEscrita;
    private javax.swing.JTextField txtParteOral;
    // End of variables declaration//GEN-END:variables
}
