/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

/**
 *
 * @author Fellipe
 */
public class EditarAula extends javax.swing.JDialog {

    /**
     * Creates new form MarcarAula
     */
    public EditarAula(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMarcacaoDetalhes = new javax.swing.JPanel();
        lblIDMarcacao = new javax.swing.JLabel();
        lblAulaMarcacao = new javax.swing.JLabel();
        lblConteudoMarcacao = new javax.swing.JLabel();
        lblProfessorMarcacao = new javax.swing.JLabel();
        lblDataHoraMarcacao = new javax.swing.JLabel();
        txtDataMarcacao = new javax.swing.JTextField();
        txtHoraMarcacao = new javax.swing.JTextField();
        txtProfessorMarcacao = new javax.swing.JTextField();
        txtAulaMarcacao = new javax.swing.JTextField();
        txtIDMarcacao = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        btnSalvarAula = new javax.swing.JButton();
        btnCancelarAula = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        pnlMarcacaoDetalhes.setBackground(new java.awt.Color(255, 255, 255));
        pnlMarcacaoDetalhes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));
        pnlMarcacaoDetalhes.setForeground(new java.awt.Color(112, 112, 112));

        lblIDMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIDMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblIDMarcacao.setText("ID");

        lblAulaMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAulaMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblAulaMarcacao.setText("Aula");

        lblConteudoMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblConteudoMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblConteudoMarcacao.setText("Conteúdo");

        lblProfessorMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProfessorMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblProfessorMarcacao.setText("Professor");

        lblDataHoraMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataHoraMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblDataHoraMarcacao.setText("Data/Hora");

        txtDataMarcacao.setBackground(new java.awt.Color(255, 255, 255));
        txtDataMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtHoraMarcacao.setBackground(new java.awt.Color(255, 255, 255));
        txtHoraMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtProfessorMarcacao.setBackground(new java.awt.Color(255, 255, 255));
        txtProfessorMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtAulaMarcacao.setBackground(new java.awt.Color(255, 255, 255));
        txtAulaMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtIDMarcacao.setBackground(new java.awt.Color(255, 255, 255));
        txtIDMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        jTextPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTextPane1.setForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout pnlMarcacaoDetalhesLayout = new javax.swing.GroupLayout(pnlMarcacaoDetalhes);
        pnlMarcacaoDetalhes.setLayout(pnlMarcacaoDetalhesLayout);
        pnlMarcacaoDetalhesLayout.setHorizontalGroup(
            pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMarcacaoDetalhesLayout.createSequentialGroup()
                                .addComponent(lblIDMarcacao)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(lblAulaMarcacao))
                        .addGap(55, 55, 55))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMarcacaoDetalhesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfessorMarcacao)
                            .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblConteudoMarcacao, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblDataHoraMarcacao, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGap(18, 18, 18)))
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProfessorMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                        .addComponent(txtDataMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtAulaMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnlMarcacaoDetalhesLayout.setVerticalGroup(
            pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDMarcacao)
                    .addComponent(txtIDMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAulaMarcacao)
                    .addComponent(txtAulaMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblConteudoMarcacao))
                    .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtProfessorMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblProfessorMarcacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDataMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataHoraMarcacao))
                .addGap(15, 15, 15))
        );

        btnSalvarAula.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvarAula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvarAula.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvarAula.setText("Salvar");

        btnCancelarAula.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelarAula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelarAula.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelarAula.setText("Cancelar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvarAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCancelarAula))
                    .addComponent(pnlMarcacaoDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(pnlMarcacaoDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelarAula)
                    .addComponent(btnSalvarAula))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                EditarAula dialog = new EditarAula(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelarAula;
    private javax.swing.JButton btnSalvarAula;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JLabel lblAulaMarcacao;
    private javax.swing.JLabel lblConteudoMarcacao;
    private javax.swing.JLabel lblDataHoraMarcacao;
    private javax.swing.JLabel lblIDMarcacao;
    private javax.swing.JLabel lblProfessorMarcacao;
    private javax.swing.JPanel pnlMarcacaoDetalhes;
    private javax.swing.JTextField txtAulaMarcacao;
    private javax.swing.JTextField txtDataMarcacao;
    private javax.swing.JTextField txtHoraMarcacao;
    private javax.swing.JTextField txtIDMarcacao;
    private javax.swing.JTextField txtProfessorMarcacao;
    // End of variables declaration//GEN-END:variables
}
