/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

import br.edu.ifnmg.poo.trabalhofinalpoo.dao.DiscenteDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Discente;

/**
 * Dialogo modal para a edição de tarefa
 *
 * @author felipe
 */
public class EditarDiscente extends javax.swing.JDialog {

    /**
     * Referência à janela de cadastro que invocou esta janela de edição.
     */
    private final CadastrarDiscente cadastroDiscente;

    /**
     * Discente recebido para edicao.
     */
    private Discente discenteEmEdicao;

    /**
     * Inicializa elementos na nova janela
     */
    public EditarDiscente(Discente discente,
            CadastrarDiscente cadastroDiscente, boolean modal) {
        super(cadastroDiscente, modal);
        initComponents();

        this.cadastroDiscente = cadastroDiscente;
        this.discenteEmEdicao = discente;

        preencherDiscente(discente);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblDadosCadastrais = new javax.swing.JLabel();
        pnlDados1 = new javax.swing.JPanel();
        lblContrato1 = new javax.swing.JLabel();
        lblNome1 = new javax.swing.JLabel();
        lblCPF1 = new javax.swing.JLabel();
        lblNascimento1 = new javax.swing.JLabel();
        txtDataNascimentoEditar = new javax.swing.JTextField();
        txtCPFEditar = new javax.swing.JTextField();
        txtContrato1 = new javax.swing.JTextField();
        txtNomeEditar = new javax.swing.JTextField();
        btnSalvar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("EditarDiscente");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        lblDadosCadastrais.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDadosCadastrais.setForeground(new java.awt.Color(0, 0, 0));
        lblDadosCadastrais.setText("Dados cadastrais");

        pnlDados1.setBackground(new java.awt.Color(255, 255, 255));
        pnlDados1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));

        lblContrato1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblContrato1.setForeground(new java.awt.Color(0, 0, 0));
        lblContrato1.setText("Contrato");

        lblNome1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNome1.setForeground(new java.awt.Color(0, 0, 0));
        lblNome1.setText("Nome");

        lblCPF1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblCPF1.setForeground(new java.awt.Color(0, 0, 0));
        lblCPF1.setText("CPF");

        lblNascimento1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblNascimento1.setForeground(new java.awt.Color(0, 0, 0));
        lblNascimento1.setText("Data de nasc.");

        txtDataNascimentoEditar.setBackground(new java.awt.Color(255, 255, 255));
        txtDataNascimentoEditar.setForeground(new java.awt.Color(0, 0, 0));
        txtDataNascimentoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDataNascimentoEditarActionPerformed(evt);
            }
        });

        txtCPFEditar.setBackground(new java.awt.Color(255, 255, 255));
        txtCPFEditar.setForeground(new java.awt.Color(0, 0, 0));

        txtContrato1.setEditable(false);
        txtContrato1.setBackground(new java.awt.Color(204, 204, 204));
        txtContrato1.setForeground(new java.awt.Color(0, 0, 0));

        txtNomeEditar.setBackground(new java.awt.Color(255, 255, 255));
        txtNomeEditar.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlDados1Layout = new javax.swing.GroupLayout(pnlDados1);
        pnlDados1.setLayout(pnlDados1Layout);
        pnlDados1Layout.setHorizontalGroup(
            pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDados1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblNascimento1)
                        .addComponent(lblNome1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblCPF1, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblContrato1))
                .addGap(12, 12, 12)
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtContrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCPFEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDataNascimentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        pnlDados1Layout.setVerticalGroup(
            pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDados1Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblContrato1)
                    .addComponent(txtContrato1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome1)
                    .addComponent(txtNomeEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCPF1)
                    .addComponent(txtCPFEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlDados1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNascimento1)
                    .addComponent(txtDataNascimentoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnSalvar.setBackground(new java.awt.Color(255, 255, 255));
        btnSalvar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSalvar.setForeground(new java.awt.Color(0, 0, 0));
        btnSalvar.setText("Salvar");
        btnSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalvarActionPerformed(evt);
            }
        });

        btnCancelar.setBackground(new java.awt.Color(255, 255, 255));
        btnCancelar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCancelar.setForeground(new java.awt.Color(0, 0, 0));
        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDadosCadastrais)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(pnlDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(lblDadosCadastrais)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlDados1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCancelar))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDataNascimentoEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDataNascimentoEditarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDataNascimentoEditarActionPerformed

    /**
     * Resposta ao clique no botão "Salvar".
     *
     * @param evt Evento capturado
     */
    private void btnSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalvarActionPerformed
        // TODO add your handling code here:
        discenteEmEdicao.setCpf(Integer.parseInt(txtCPFEditar.getText()));
        discenteEmEdicao.setNome(txtNomeEditar.getText());
        discenteEmEdicao.setNascimento(txtDataNascimentoEditar.getText());

        new DiscenteDao().salvar(discenteEmEdicao);
        cadastroDiscente.atualizarModelo(discenteEmEdicao);
        // fecha janela
        dispose();
    }//GEN-LAST:event_btnSalvarActionPerformed

    /**
     * Fecha a janela ao clicar no botão "Cancelar"
     *
     * @param evt Evento capturado
     */
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    /**
     * Extrai dados do discente recebido e popula os componentes da janela com
     * seus respectivos valores.
     *
     * @param discente Objeto "Discente" recebido
     */
    public void preencherDiscente(Discente discente) {
        txtCPFEditar.setText(Integer.toString(discente.getCpf()));
        txtNomeEditar.setText(discente.getNome());
        txtDataNascimentoEditar.setText(discente.getNascimento());
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnHistorico;
    private javax.swing.JButton btnSalvar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCPF;
    private javax.swing.JLabel lblCPF1;
    private javax.swing.JLabel lblContrato;
    private javax.swing.JLabel lblContrato1;
    private javax.swing.JLabel lblDadosCadastrais;
    private javax.swing.JLabel lblNascimento;
    private javax.swing.JLabel lblNascimento1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNome1;
    private javax.swing.JPanel pnlDados;
    private javax.swing.JPanel pnlDados1;
    private javax.swing.JTextField txtCPF;
    private javax.swing.JTextField txtCPFEditar;
    private javax.swing.JTextField txtContrato;
    private javax.swing.JTextField txtContrato1;
    private javax.swing.JTextField txtDataNascimento;
    private javax.swing.JTextField txtDataNascimentoEditar;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNomeEditar;
    // End of variables declaration//GEN-END:variables
}
