/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.edu.ifnmg.poo.trabalhofinalpoo.gui;

import br.edu.ifnmg.poo.trabalhofinalpoo.dao.DiscenteDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.dao.DisciplinaDao;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Discente;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Disciplina;
import java.util.List;
import javax.swing.DefaultListModel;
import br.edu.ifnmg.poo.trabalhofinalpoo.entity.Entidade;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Fellipe
 */
public class GerenciarAula extends javax.swing.JFrame {
    
    private DefaultListModel<Disciplina> lstHorariosMarcacaoModel;
    private DefaultListModel<Discente> lstSelecionarAlunoModel;
    
    private int IndiceHorarioSelecionado;
    private int IndiceDiscenteSelecionarSelecionado;
    
    public GerenciarAula() {
        
        lstHorariosMarcacaoModel = new DefaultListModel<>();
        lstSelecionarAlunoModel = new DefaultListModel<>();
        
        List<Disciplina> horarios = new DisciplinaDao().localizarTodos();
        List<Discente> discentes = new DiscenteDao().localizarTodos();
        
        lstHorariosMarcacaoModel.addAll(horarios);
        lstSelecionarAlunoModel.addAll(discentes);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popUpMenu = new javax.swing.JPopupMenu();
        mnuEditar = new javax.swing.JMenuItem();
        pnlMarcacaoAula = new javax.swing.JPanel();
        lblDadosMarcacao = new javax.swing.JLabel();
        lblHorariosDisponiveis = new javax.swing.JLabel();
        btnMarcarAula = new javax.swing.JButton();
        pnlDetalhesMarcacao = new javax.swing.JPanel();
        pnlMarcacaoDetalhes = new javax.swing.JPanel();
        lblIDMarcacao = new javax.swing.JLabel();
        lblAulaMarcacao = new javax.swing.JLabel();
        lblConteudoMarcacao = new javax.swing.JLabel();
        lblProfessorMarcacao = new javax.swing.JLabel();
        lblDataHoraMarcacao = new javax.swing.JLabel();
        txtDataMarcacao = new javax.swing.JTextField();
        txtHoraMarcacao = new javax.swing.JTextField();
        txtProfessorMarcacao = new javax.swing.JTextField();
        txtConteudoMarcacao = new javax.swing.JTextField();
        txtAulaMarcacao = new javax.swing.JTextField();
        txtIDMarcacao = new javax.swing.JTextField();
        lblDetalhesAulaMarcacao = new javax.swing.JLabel();
        scrHorariosMarcacao = new javax.swing.JScrollPane();
        lstAlunos = new javax.swing.JList<>();
        scrListaSelecionarAluno = new javax.swing.JScrollPane();
        lstSelecionarAluno = new javax.swing.JList<>();
        btnNovoAula = new javax.swing.JButton();
        btnEditarAula = new javax.swing.JButton();
        btnExcluirAula = new javax.swing.JButton();

        mnuEditar.setMnemonic('e');
        mnuEditar.setText("Editar");
        popUpMenu.add(mnuEditar);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlMarcacaoAula.setBackground(new java.awt.Color(255, 255, 255));

        lblDadosMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDadosMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblDadosMarcacao.setText("Selecionar aluno");

        lblHorariosDisponiveis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblHorariosDisponiveis.setForeground(new java.awt.Color(0, 0, 0));
        lblHorariosDisponiveis.setText("Horários disponíveis");

        btnMarcarAula.setBackground(new java.awt.Color(255, 255, 255));
        btnMarcarAula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMarcarAula.setForeground(new java.awt.Color(0, 0, 0));
        btnMarcarAula.setText("Marcar");
        btnMarcarAula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarcarAulaActionPerformed(evt);
            }
        });

        pnlDetalhesMarcacao.setBackground(new java.awt.Color(252, 252, 252));

        pnlMarcacaoDetalhes.setBackground(new java.awt.Color(255, 255, 255));
        pnlMarcacaoDetalhes.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(112, 112, 112)));
        pnlMarcacaoDetalhes.setForeground(new java.awt.Color(112, 112, 112));

        lblIDMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblIDMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblIDMarcacao.setText("ID");

        lblAulaMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblAulaMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblAulaMarcacao.setText("Aula");

        lblConteudoMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblConteudoMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblConteudoMarcacao.setText("Conteúdo");

        lblProfessorMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblProfessorMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblProfessorMarcacao.setText("Professor");

        lblDataHoraMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDataHoraMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblDataHoraMarcacao.setText("Data/Hora");

        txtDataMarcacao.setBackground(new java.awt.Color(204, 204, 204));
        txtDataMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtHoraMarcacao.setBackground(new java.awt.Color(204, 204, 204));
        txtHoraMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtProfessorMarcacao.setBackground(new java.awt.Color(204, 204, 204));
        txtProfessorMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtConteudoMarcacao.setBackground(new java.awt.Color(204, 204, 204));
        txtConteudoMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtAulaMarcacao.setBackground(new java.awt.Color(204, 204, 204));
        txtAulaMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        txtIDMarcacao.setBackground(new java.awt.Color(204, 204, 204));
        txtIDMarcacao.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout pnlMarcacaoDetalhesLayout = new javax.swing.GroupLayout(pnlMarcacaoDetalhes);
        pnlMarcacaoDetalhes.setLayout(pnlMarcacaoDetalhesLayout);
        pnlMarcacaoDetalhesLayout.setHorizontalGroup(
            pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMarcacaoDetalhesLayout.createSequentialGroup()
                            .addComponent(lblIDMarcacao)
                            .addGap(0, 0, Short.MAX_VALUE))
                        .addComponent(lblAulaMarcacao))
                    .addComponent(lblConteudoMarcacao)
                    .addComponent(lblProfessorMarcacao)
                    .addComponent(lblDataHoraMarcacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtProfessorMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConteudoMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAulaMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIDMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                        .addComponent(txtDataMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHoraMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        pnlMarcacaoDetalhesLayout.setVerticalGroup(
            pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcacaoDetalhesLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDMarcacao)
                    .addComponent(txtIDMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAulaMarcacao)
                    .addComponent(txtAulaMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblConteudoMarcacao)
                    .addComponent(txtConteudoMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfessorMarcacao)
                    .addComponent(txtProfessorMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(pnlMarcacaoDetalhesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDataHoraMarcacao)
                    .addComponent(txtDataMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHoraMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 41, Short.MAX_VALUE))
        );

        txtDataMarcacao.getAccessibleContext().setAccessibleName("");

        lblDetalhesAulaMarcacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        lblDetalhesAulaMarcacao.setForeground(new java.awt.Color(0, 0, 0));
        lblDetalhesAulaMarcacao.setText("Detalhes da aula");

        javax.swing.GroupLayout pnlDetalhesMarcacaoLayout = new javax.swing.GroupLayout(pnlDetalhesMarcacao);
        pnlDetalhesMarcacao.setLayout(pnlDetalhesMarcacaoLayout);
        pnlDetalhesMarcacaoLayout.setHorizontalGroup(
            pnlDetalhesMarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlDetalhesMarcacaoLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addGroup(pnlDetalhesMarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDetalhesAulaMarcacao)
                    .addComponent(pnlMarcacaoDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        pnlDetalhesMarcacaoLayout.setVerticalGroup(
            pnlDetalhesMarcacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlDetalhesMarcacaoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblDetalhesAulaMarcacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlMarcacaoDetalhes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        lstAlunos.setBackground(new java.awt.Color(255, 255, 255));
        lstAlunos.setForeground(new java.awt.Color(0, 0, 0));
        lstAlunos.setModel(lstHorariosMarcacaoModel);
        lstAlunos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstAlunosMouseClicked(evt);
            }
        });
        scrHorariosMarcacao.setViewportView(lstAlunos);

        lstSelecionarAluno.setBackground(new java.awt.Color(255, 255, 255));
        lstSelecionarAluno.setForeground(new java.awt.Color(0, 0, 0));
        lstSelecionarAluno.setModel(lstSelecionarAlunoModel);
        scrListaSelecionarAluno.setViewportView(lstSelecionarAluno);

        btnNovoAula.setBackground(new java.awt.Color(255, 255, 255));
        btnNovoAula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnNovoAula.setForeground(new java.awt.Color(0, 0, 0));
        btnNovoAula.setText("Novo");
        btnNovoAula.setToolTipText("");

        btnEditarAula.setBackground(new java.awt.Color(255, 255, 255));
        btnEditarAula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEditarAula.setForeground(new java.awt.Color(0, 0, 0));
        btnEditarAula.setText("Editar");

        btnExcluirAula.setBackground(new java.awt.Color(255, 255, 255));
        btnExcluirAula.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnExcluirAula.setForeground(new java.awt.Color(0, 0, 0));
        btnExcluirAula.setText("Excluir");

        javax.swing.GroupLayout pnlMarcacaoAulaLayout = new javax.swing.GroupLayout(pnlMarcacaoAula);
        pnlMarcacaoAula.setLayout(pnlMarcacaoAulaLayout);
        pnlMarcacaoAulaLayout.setHorizontalGroup(
            pnlMarcacaoAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcacaoAulaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnlMarcacaoAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblDadosMarcacao)
                    .addComponent(lblHorariosDisponiveis)
                    .addComponent(scrHorariosMarcacao)
                    .addComponent(scrListaSelecionarAluno)
                    .addGroup(pnlMarcacaoAulaLayout.createSequentialGroup()
                        .addComponent(btnNovoAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEditarAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnExcluirAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                        .addComponent(btnMarcarAula)))
                .addGap(25, 25, 25)
                .addComponent(pnlDetalhesMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        pnlMarcacaoAulaLayout.setVerticalGroup(
            pnlMarcacaoAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMarcacaoAulaLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblDadosMarcacao)
                .addGap(3, 3, 3)
                .addComponent(scrListaSelecionarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblHorariosDisponiveis)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrHorariosMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(pnlMarcacaoAulaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMarcarAula)
                    .addComponent(btnExcluirAula)
                    .addComponent(btnEditarAula)
                    .addComponent(btnNovoAula))
                .addContainerGap(28, Short.MAX_VALUE))
            .addGroup(pnlMarcacaoAulaLayout.createSequentialGroup()
                .addComponent(pnlDetalhesMarcacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlMarcacaoAula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMarcacaoAula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditarPresencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarPresencaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnEditarPresencaActionPerformed

    private void lstAlunosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstAlunosMouseClicked
        // TODO add your handling code here:
        txtAulaMarcacao.setText("Hello");
    }//GEN-LAST:event_lstAlunosMouseClicked

    private void btnMarcarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarcarAulaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnMarcarAulaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciarAula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciarAula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarAula;
    private javax.swing.JButton btnExcluirAula;
    private javax.swing.JButton btnMarcarAula;
    private javax.swing.JButton btnNovoAula;
    private javax.swing.JLabel lblAulaMarcacao;
    private javax.swing.JLabel lblConteudoMarcacao;
    private javax.swing.JLabel lblDadosMarcacao;
    private javax.swing.JLabel lblDataHoraMarcacao;
    private javax.swing.JLabel lblDetalhesAulaMarcacao;
    private javax.swing.JLabel lblHorariosDisponiveis;
    private javax.swing.JLabel lblIDMarcacao;
    private javax.swing.JLabel lblProfessorMarcacao;
    private javax.swing.JList<Disciplina> lstAlunos;
    private javax.swing.JList<Discente> lstSelecionarAluno;
    private javax.swing.JMenuItem mnuEditar;
    private javax.swing.JPanel pnlDetalhesMarcacao;
    private javax.swing.JPanel pnlMarcacaoAula;
    private javax.swing.JPanel pnlMarcacaoDetalhes;
    private javax.swing.JPopupMenu popUpMenu;
    private javax.swing.JScrollPane scrHorariosMarcacao;
    private javax.swing.JScrollPane scrListaSelecionarAluno;
    private javax.swing.JTextField txtAulaMarcacao;
    private javax.swing.JTextField txtConteudoMarcacao;
    private javax.swing.JTextField txtDataMarcacao;
    private javax.swing.JTextField txtHoraMarcacao;
    private javax.swing.JTextField txtIDMarcacao;
    private javax.swing.JTextField txtProfessorMarcacao;
    // End of variables declaration//GEN-END:variables
}
